### ISSUE TITLE
Auto-commit actions?

### ISSUE THREAD

**Issue by chrissimpkins** [googlefonts/googlesans-flex#14]
What does this do?

```
- uses: stefanzweifel/git-auto-commit-action@v4
      name: First-run setup
      if: github.repository != 'googlefonts/googlefonts-project-template'
      with:
        file_pattern: .init.stamp README.md requirements.txt OFL.txt
        commit_message: "Personalize for this repo"
```

It lists a file (OFL.txt) that is now removed from the repository because it is not relevant to this project (#5)
