### ISSUE TITLE
Add Static Instances

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#897]
Each family will have 18 styles: 9 weights from 100 to 900 in Roman and Italic.

Locations
1. Google Sans Flex 144-opsz 100-wdth 0-ROND
2. Google Sans Flex UltraCondensed 144-opsz 50-wdth 0-ROND
3. Google Sans Flex SuperCondensed 144-opsz 25-wdth 0-ROND
4. Google Sans Flex Rounded 144-opsz 100-wdth 100-ROND
5. Google Sans Flex Text 12-opsz 100-wdth 0-ROND
6. Google Sans Flex ExtraExpanded 144-opsz 150-wdth 0-ROND

**Comment by belluzj** [comment]
Locations = 6 separate families for Workspace, each with 18 styles. "Google Sans Flex UltraCondensed" = family name

How to make the families? Slice from VF probably, only make statics.

This is only for workspace. Not to do any new release work (= don't increase version number, but attach new ZIP to previous release)

We were happy with the cut instances from Google Sans, so we can reuse the script from there: https://github.com/googlefonts/googlesans/blob/main/scripts/internal/cut-instances.py

Also make sure, within a family, to link between regular and bold, regular and italic etc.

We'll need to ignore some family name length warnings from FontBakery (max 32) because the names will be bigger than that, but it's not an issue for Workspace, as some testing showed.

In terms of pipeline, don't run on every build, but do run on release. Produce a separate ZIP with name StaticsForWorkspace, or a Workspace folder under the release directory.

**Comment by RickyDaMa** [comment]
Related, from my attempt to use gftools for this: https://github.com/googlefonts/gftools/issues/849

**Comment by RickyDaMa** [comment]
Hey @simoncozens, some additional context about what we're trying to pull off here:

* we're wanting to slice statics from the VF
* we've got 108 well-defined statics, so we know the family/style names in advance (generated by a [script](https://github.com/googlefonts/googlesans-flex/blob/d7d35f6c3528b513ad579781b37decdc731d14c3/scripts/generate_release_config.py))

Example config: 

<details>
<summary>release.yaml</summary>

```yml
# This file was @generated by generate_workspace_statics_config.py
# Do not modify

buildOTF: false
buildStatic: true
buildWebfont: false
familyName: Google Sans Flex
instances:
  GoogleSansFlex[GRAD,ROND,opsz,slnt,wdth,wght].ttf:
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 100.0
    familyName: Google Sans Flex
    styleName: Thin
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 200.0
    familyName: Google Sans Flex
    styleName: ExtraLight
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 300.0
    familyName: Google Sans Flex
    styleName: Light
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 400.0
    familyName: Google Sans Flex
    styleName: Regular
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 500.0
    familyName: Google Sans Flex
    styleName: Medium
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 600.0
    familyName: Google Sans Flex
    styleName: SemiBold
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 700.0
    familyName: Google Sans Flex
    styleName: Bold
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 800.0
    familyName: Google Sans Flex
    styleName: ExtraBold
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 900.0
    familyName: Google Sans Flex
    styleName: Black
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 100.0
    familyName: Google Sans Flex
    styleName: Thin Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 200.0
    familyName: Google Sans Flex
    styleName: ExtraLight Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 300.0
    familyName: Google Sans Flex
    styleName: Light Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 400.0
    familyName: Google Sans Flex
    styleName: Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 500.0
    familyName: Google Sans Flex
    styleName: Medium Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 600.0
    familyName: Google Sans Flex
    styleName: SemiBold Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 700.0
    familyName: Google Sans Flex
    styleName: Bold Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 800.0
    familyName: Google Sans Flex
    styleName: ExtraBold Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 100
      wght: 900.0
    familyName: Google Sans Flex
    styleName: Black Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 100.0
    familyName: Google Sans Flex UltraCondensed
    styleName: Thin
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 200.0
    familyName: Google Sans Flex UltraCondensed
    styleName: ExtraLight
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 300.0
    familyName: Google Sans Flex UltraCondensed
    styleName: Light
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 400.0
    familyName: Google Sans Flex UltraCondensed
    styleName: Regular
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 500.0
    familyName: Google Sans Flex UltraCondensed
    styleName: Medium
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 600.0
    familyName: Google Sans Flex UltraCondensed
    styleName: SemiBold
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 700.0
    familyName: Google Sans Flex UltraCondensed
    styleName: Bold
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 800.0
    familyName: Google Sans Flex UltraCondensed
    styleName: ExtraBold
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 900.0
    familyName: Google Sans Flex UltraCondensed
    styleName: Black
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 100.0
    familyName: Google Sans Flex UltraCondensed
    styleName: Thin Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 200.0
    familyName: Google Sans Flex UltraCondensed
    styleName: ExtraLight Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 300.0
    familyName: Google Sans Flex UltraCondensed
    styleName: Light Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 400.0
    familyName: Google Sans Flex UltraCondensed
    styleName: Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 500.0
    familyName: Google Sans Flex UltraCondensed
    styleName: Medium Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 600.0
    familyName: Google Sans Flex UltraCondensed
    styleName: SemiBold Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 700.0
    familyName: Google Sans Flex UltraCondensed
    styleName: Bold Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 800.0
    familyName: Google Sans Flex UltraCondensed
    styleName: ExtraBold Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 50
      wght: 900.0
    familyName: Google Sans Flex UltraCondensed
    styleName: Black Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 100.0
    familyName: Google Sans Flex SuperCondensed
    styleName: Thin
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 200.0
    familyName: Google Sans Flex SuperCondensed
    styleName: ExtraLight
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 300.0
    familyName: Google Sans Flex SuperCondensed
    styleName: Light
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 400.0
    familyName: Google Sans Flex SuperCondensed
    styleName: Regular
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 500.0
    familyName: Google Sans Flex SuperCondensed
    styleName: Medium
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 600.0
    familyName: Google Sans Flex SuperCondensed
    styleName: SemiBold
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 700.0
    familyName: Google Sans Flex SuperCondensed
    styleName: Bold
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 800.0
    familyName: Google Sans Flex SuperCondensed
    styleName: ExtraBold
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 900.0
    familyName: Google Sans Flex SuperCondensed
    styleName: Black
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 100.0
    familyName: Google Sans Flex SuperCondensed
    styleName: Thin Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 200.0
    familyName: Google Sans Flex SuperCondensed
    styleName: ExtraLight Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 300.0
    familyName: Google Sans Flex SuperCondensed
    styleName: Light Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 400.0
    familyName: Google Sans Flex SuperCondensed
    styleName: Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 500.0
    familyName: Google Sans Flex SuperCondensed
    styleName: Medium Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 600.0
    familyName: Google Sans Flex SuperCondensed
    styleName: SemiBold Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 700.0
    familyName: Google Sans Flex SuperCondensed
    styleName: Bold Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 800.0
    familyName: Google Sans Flex SuperCondensed
    styleName: ExtraBold Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 25
      wght: 900.0
    familyName: Google Sans Flex SuperCondensed
    styleName: Black Italic
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 100.0
    familyName: Google Sans Flex Rounded
    styleName: Thin
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 200.0
    familyName: Google Sans Flex Rounded
    styleName: ExtraLight
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 300.0
    familyName: Google Sans Flex Rounded
    styleName: Light
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 400.0
    familyName: Google Sans Flex Rounded
    styleName: Regular
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 500.0
    familyName: Google Sans Flex Rounded
    styleName: Medium
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 600.0
    familyName: Google Sans Flex Rounded
    styleName: SemiBold
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 700.0
    familyName: Google Sans Flex Rounded
    styleName: Bold
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 800.0
    familyName: Google Sans Flex Rounded
    styleName: ExtraBold
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 900.0
    familyName: Google Sans Flex Rounded
    styleName: Black
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 100.0
    familyName: Google Sans Flex Rounded
    styleName: Thin Italic
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 200.0
    familyName: Google Sans Flex Rounded
    styleName: ExtraLight Italic
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 300.0
    familyName: Google Sans Flex Rounded
    styleName: Light Italic
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 400.0
    familyName: Google Sans Flex Rounded
    styleName: Italic
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 500.0
    familyName: Google Sans Flex Rounded
    styleName: Medium Italic
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 600.0
    familyName: Google Sans Flex Rounded
    styleName: SemiBold Italic
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 700.0
    familyName: Google Sans Flex Rounded
    styleName: Bold Italic
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 800.0
    familyName: Google Sans Flex Rounded
    styleName: ExtraBold Italic
  - coordinates:
      ROND: 100
      opsz: 144
      wdth: 100
      wght: 900.0
    familyName: Google Sans Flex Rounded
    styleName: Black Italic
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 100.0
    familyName: Google Sans Flex Text
    styleName: Thin
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 200.0
    familyName: Google Sans Flex Text
    styleName: ExtraLight
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 300.0
    familyName: Google Sans Flex Text
    styleName: Light
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 400.0
    familyName: Google Sans Flex Text
    styleName: Regular
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 500.0
    familyName: Google Sans Flex Text
    styleName: Medium
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 600.0
    familyName: Google Sans Flex Text
    styleName: SemiBold
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 700.0
    familyName: Google Sans Flex Text
    styleName: Bold
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 800.0
    familyName: Google Sans Flex Text
    styleName: ExtraBold
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 900.0
    familyName: Google Sans Flex Text
    styleName: Black
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 100.0
    familyName: Google Sans Flex Text
    styleName: Thin Italic
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 200.0
    familyName: Google Sans Flex Text
    styleName: ExtraLight Italic
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 300.0
    familyName: Google Sans Flex Text
    styleName: Light Italic
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 400.0
    familyName: Google Sans Flex Text
    styleName: Italic
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 500.0
    familyName: Google Sans Flex Text
    styleName: Medium Italic
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 600.0
    familyName: Google Sans Flex Text
    styleName: SemiBold Italic
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 700.0
    familyName: Google Sans Flex Text
    styleName: Bold Italic
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 800.0
    familyName: Google Sans Flex Text
    styleName: ExtraBold Italic
  - coordinates:
      ROND: 0
      opsz: 12
      wdth: 100
      wght: 900.0
    familyName: Google Sans Flex Text
    styleName: Black Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 100.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: Thin
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 200.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: ExtraLight
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 300.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: Light
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 400.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: Regular
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 500.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: Medium
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 600.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: SemiBold
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 700.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: Bold
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 800.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: ExtraBold
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 900.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: Black
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 100.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: Thin Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 200.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: ExtraLight Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 300.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: Light Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 400.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 500.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: Medium Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 600.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: SemiBold Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 700.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: Bold Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 800.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: ExtraBold Italic
  - coordinates:
      ROND: 0
      opsz: 144
      wdth: 150
      wght: 900.0
    familyName: Google Sans Flex ExtraExpanded
    styleName: Black Italic
removeOutlineOverlaps: false
reverseOutlineDirection: false
sources:
- GoogleSansFlex.designspace
stat:
  GoogleSansFlex[GRAD,ROND,opsz,slnt,wdth,wght].ttf:
  - name: Optical Size
    tag: opsz
    values:
    - flags: 0
      name: 6pt
      value: 6.0
    - flags: 0
      name: 8pt
      value: 8.0
    - flags: 0
      name: 9pt
      value: 9.0
    - flags: 0
      name: 10pt
      value: 10.0
    - flags: 0
      name: 11pt
      value: 11.0
    - flags: 0
      name: 12pt
      value: 12.0
    - flags: 0
      name: 14pt
      value: 14.0
    - flags: 0
      name: 16pt
      value: 16.0
    - flags: 0
      name: 17pt
      value: 17.0
    - flags: 2
      name: 18pt
      value: 18.0
    - flags: 0
      name: 20pt
      value: 20.0
    - flags: 0
      name: 24pt
      value: 24.0
    - flags: 0
      name: 28pt
      value: 28.0
    - flags: 0
      name: 36pt
      value: 36.0
    - flags: 0
      name: 48pt
      value: 48.0
    - flags: 0
      name: 60pt
      value: 60.0
    - flags: 0
      name: 72pt
      value: 72.0
    - flags: 0
      name: 96pt
      value: 96.0
    - flags: 0
      name: 120pt
      value: 120.0
    - flags: 0
      name: 144pt
      value: 144.0
  - name: Width
    tag: wdth
    values:
    - flags: 0
      name: SuperCondensed
      value: 25.0
    - flags: 0
      name: UltraCondensed
      value: 50.0
    - flags: 0
      name: ExtraCondensed
      value: 62.5
    - flags: 0
      name: Condensed
      value: 75.0
    - flags: 0
      name: SemiCondensed
      value: 87.5
    - flags: 2
      name: Normal
      value: 100.0
    - flags: 0
      name: SemiExpanded
      value: 112.5
    - flags: 0
      name: Expanded
      value: 125.0
    - flags: 0
      name: ExtraExpanded
      nominalValue: 150.0
      rangeMaxValue: 151.0
      rangeMinValue: 150.0
      value: 150.0
  - name: Weight
    tag: wght
    values:
    - flags: 0
      name: Hairline
      value: 1.0
    - flags: 0
      name: Thin
      value: 100.0
    - flags: 0
      name: ExtraLight
      value: 200.0
    - flags: 0
      name: Light
      value: 300.0
    - flags: 2
      linkedValue: 700.0
      name: Regular
      value: 400.0
    - flags: 0
      name: Medium
      value: 500.0
    - flags: 0
      name: SemiBold
      value: 600.0
    - flags: 0
      name: Bold
      value: 700.0
    - flags: 0
      name: ExtraBold
      value: 800.0
    - flags: 0
      name: Black
      value: 900.0
    - flags: 0
      name: UltraBlack
      value: 1000.0
  - name: Grade
    tag: GRAD
    values:
    - flags: 2
      name: Normal
      value: 0.0
  - name: Roundness
    tag: ROND
    values:
    - flags: 2
      name: Default
      value: 0.0
    - flags: 0
      name: Rounded
      value: 100.0
  - name: Slant
    tag: slnt
    values:
    - flags: 2
      linkedValue: -10
      name: Default
      value: 0
    - flags: 0
      name: Italic
      value: -10

```

</details>

For now, I'm adapting the cut-instances script mentioned above to do the job instead of relying on gftools - it just made sense to try gftools first since it already had the feature in the stable version (just bugged, hence the issue)

I hope this and this issue helps explain our use case :)
