### ISSUE TITLE
Fix shaping issues in Igbo and Yoruba - check anchors

### ISSUE THREAD

**Issue by MariannaPaszkowska** [googlefonts/googlesans-flex#991]
Hi @octaviopardo,
Shapergot reports an issue there, gravecomb and acutecomb are not attaching to those glyphs. Could you review the anchors in those glyphs?

```
 uni1ECB
 uni1ECA
 uni1EE5
 uni1EE4
 uni1EB9
 uni1EB8
 uni1ECD
 uni1ECC
```

```
Igbo:
    PASS: All base glyphs were present in the font
    PASS: All mark glyphs were present in the font
    PASS: All auxiliary glyphs were present in the font
    PASS: No unattached mark glyphs were produced shaping the text 'D l E n T y b CH H z J ny F P Y gw h sh v I N M kw gb j R r e G d ẹ u Ọ NY Z m ṅ w ch nw O k L s Ẹ KW ọ V W SH i GW ị Ṅ o g B A NW ụ p f U K GH gh S Ụ GB t KP Ị a kp'
    FAIL: Shaper didn't attach acutecomb to uni1ECB
    FAIL: Shaper didn't attach acutecomb to uni1ECA
    FAIL: Shaper didn't attach gravecomb to uni1ECB
    FAIL: Shaper didn't attach gravecomb to uni1ECA
    FAIL: Shaper didn't attach acutecomb to uni1ECD
    FAIL: Shaper didn't attach acutecomb to uni1ECC
    FAIL: Shaper didn't attach gravecomb to uni1ECD
    FAIL: Shaper didn't attach gravecomb to uni1ECC
    FAIL: Shaper didn't attach acutecomb to uni1EE5
    FAIL: Shaper didn't attach acutecomb to uni1EE4
    FAIL: Shaper didn't attach gravecomb to uni1EE5
    FAIL: Shaper didn't attach gravecomb to uni1EE4
    WARN: No variant glyphs were found for .notdef
```
```
  Yoruba:
    PASS: All base glyphs were present in the font
    PASS: All mark glyphs were present in the font
    PASS: All auxiliary glyphs were present in the font
    FAIL: Shaper didn't attach gravecomb to uni1EB9
    FAIL: Shaper didn't attach gravecomb to uni1EB8
    FAIL: Shaper didn't attach acutecomb to uni1ECD
    FAIL: Shaper didn't attach acutecomb to uni1ECC
    FAIL: Shaper didn't attach gravecomb to uni1ECD
    FAIL: Shaper didn't attach acutecomb to uni1EB9
    FAIL: Shaper didn't attach gravecomb to uni1ECC
    FAIL: Shaper didn't attach acutecomb to uni1EB8
    FAIL: Shaper didn't attach acutecomb to uni1EB9
    FAIL: Shaper didn't attach acutecomb to uni1EB8
    FAIL: Shaper didn't attach gravecomb to uni1EB9
    FAIL: Shaper didn't attach gravecomb to uni1EB8
    FAIL: Shaper didn't attach acutecomb to uni1ECD
    FAIL: Shaper didn't attach acutecomb to uni1ECC
    FAIL: Shaper didn't attach gravecomb to uni1ECD
    FAIL: Shaper didn't attach gravecomb to uni1ECC
```

Tested build: https://github.com/googlefonts/googlesans-flex/actions/runs/10042901823
